before:
  hooks:
    - go mod tidy
    - go mod download
blobs:
  - provider: s3
    bucket: mantil-downloads
    region: eu-central-1
    folder: releases/cli/{{ .Tag }}
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
    main: ./cli
    ldflags:
      - -X "github.com/mantil-io/mantil/cli/build.tag={{ .Env.tag }}"
      - -X "github.com/mantil-io/mantil/cli/build.dev={{ .Env.dev }}"
      - -X "github.com/mantil-io/mantil/cli/build.ontag={{ .Env.on_tag }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: mantil-io
      name: homebrew-mantil
    description: "Mantil CLI"
    skip_upload: auto
    folder: Formula
    dependencies:
      - name: go
    url_template: "releases.mantil.io/{{ .Tag }}/{{ .ArtifactName }}"
