before:
  hooks:
    - go mod tidy
    - go mod download
blobs:
  - provider: s3
    bucket: mantil-downloads
    region: eu-central-1
    folder: releases/cli/{{ .Version }}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    main: ./cmd/mantil
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: mantil-io
      name: homebrew-mantil
    description: "Mantil CLI"
    skip_upload: auto
    dependancies:
      - name: go
