// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/mantil.go"
	"github.com/mantil-io/mantil/registration/backend/api/register"
)

func main() {
	var api = register.New()
	mantil.LambdaHandler(api)
}
