// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/mantil.go"
	"github.com/mantil-io/mantil/signup/backend/api/signup"
)

func main() {
	var api = signup.New()
	mantil.LambdaHandler(api)
}
