AWSTemplateFormatVersion: 2010-09-09
Resources:
  MantilSetupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: {{.Name}}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: {{.Name}}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PATCH
                  - apigateway:DELETE
                  - apigateway:PUT
                  - apigateway:TagResource
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::mantil-releases*/*
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:AddPermission
                  - lambda:ListVersionsByFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionCodeSigningConfig
                  - lambda:GetPolicy
                  - lambda:DeleteFunction
                  - lambda:RemovePermission
                  - lambda:GetLayerVersion
                  - lambda:UpdateFunctionCode
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionConfiguration
                Resource:
                  - arn:aws:lambda:*:*:function:mantil-*-{{.Suffix}}
                  - arn:aws:lambda:*:*:layer:*:*
              - Effect: Allow
                Action:
                  - iam:GetRole
                Resource:
                  - arn:aws:iam::*:role/*
              - Effect: Allow
                Action:
                  - iam:GetRolePolicy
                  - iam:ListAttachedRolePolicies
                  - iam:CreateRole
                  - iam:ListRolePolicies
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:DeleteRole
                  - iam:ListInstanceProfilesForRole
                  - iam:TagRole
                  - iam:PassRole
                Resource:
                  - arn:aws:iam::*:role/mantil-*-{{.Suffix}}
                  - arn:aws:iam::*:role/{{.APIGatewayLogsRole}}
              - Effect: Allow
                Action:
                 - s3:CreateBucket
                 - s3:PutBucketTagging
                 - s3:PutLifecycleConfiguration
                 - s3:DeleteBucket
                 - s3:ListBucket
                 - s3:PutObject
                 - s3:GetObject
                 - s3:DeleteObject
                 - s3:DeleteObjectVersion
                Resource:
                  - arn:aws:s3:::mantil-{{.Suffix}}
                  - arn:aws:s3:::mantil-{{.Suffix}}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DeleteLogGroup
                  - logs:ListTagsLogGroup
                Resource:
                  - arn:aws:logs:*:*:log-group:*-{{.Suffix}}
                  - arn:aws:logs:*:*:log-group:*-{{.Suffix}}:log-stream:*
              - Effect: Allow
                Action:
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:PutRetentionPolicy
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                  - logs:GetLogDelivery
                  - logs:CreateLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:ListLogDeliveries
                  - logs:DeleteLogDelivery
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:AddTagsToResource
                  - ssm:ListTagsForResource
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:DescribeParameters
                  - ssm:DeleteParameter
                Resource:
                  - "*"
  MantilSetupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: {{.Name}}
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 900
      MemorySize: 1769
      Architectures: ['arm64']
      Layers:
        - arn:aws:lambda:{{.Region}}:477361877445:layer:terraform-layer:1
      Code:
        S3Bucket: {{.Bucket}}
        S3Key: {{.S3Key}}
      Role: !GetAtt
        - MantilSetupRole
        - Arn
    DependsOn:
      - MantilSetupRole
      - MantilSetupLambdaLogGroup
  MantilSetupLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/{{.Name}}
      RetentionInDays: 14
