package cmd

import (
	"github.com/mantil-io/mantil/cli/build"
	"github.com/mantil-io/mantil/cli/controller"
	"github.com/mantil-io/mantil/cli/ui"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func Execute() error {
	ec, err := root().ExecuteC()
	if err == nil {
		return nil
	}

	// show usage in case of ArgumentError
	var ae *controller.ArgumentError
	if errors.As(err, &ae) {
		ui.Error(ae)
		ec.Usage()
		return err
	}

	// if the error is not wrapped then it is probably generated by cobra
	// show usage because that is breaking some arguments constraints
	if errors.Unwrap(err) == nil {
		ui.Error(err)
		ec.Usage()
		return err
	}

	// in other cases show error without usage
	ui.Error(err)
	return err
}

func root() *cobra.Command {
	var cmd = &cobra.Command{
		Use:           "mantil",
		Short:         "Makes serverless development with Go and AWS Lambda joyful",
		Version:       build.Version().String(),
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	// no-color is handled in cli/log pacakge
	cmd.PersistentFlags().Bool("no-color", false, "don't use colors in output")
	cmd.PersistentFlags().Bool("help", false, "show command help") // move help to global commands
	cmd.Flags().Bool("version", false, "show mantil version")      // remove -v shortcut for version

	add := func(factory func() *cobra.Command) {
		sub := factory()
		cmd.AddCommand(sub)
	}
	subCommands := []func() *cobra.Command{
		newEnvCommand,
		newInvokeCommand,
		newLogsCommand,
		newNewCommand,
		newTestCommand,
		newWatchCommand,
		newDeployCommand,
		newGenerateCommand,
		newAwsCommand,
		newStageCommand,

		// for testing:
		//examples.NewErrorsCommand,
		//examples.NewArgsCommand,
	}
	for _, sub := range subCommands {
		add(sub)
	}
	return cmd
}

func GenDoc(dir string) error {
	cmd := root()
	cmd.DisableAutoGenTag = true
	return doc.GenMarkdownTree(cmd, dir)
}
