#!/bin/bash

echo "functions to delete:"
aws lambda list-functions | jq -r '.Functions | .[] | .FunctionName' |
while read uname1; do
  echo "  $uname1";
done

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

aws lambda list-functions | jq -r '.Functions | .[] | .FunctionName' |
while read uname1; do
  echo "deleting $uname1";
  aws lambda delete-function --function-name $uname1;
done
