// Code generated by mantil DO NOT EDIT
package main

import (
	"github.com/mantil-io/mantil.go"
	"github.com/mantil-io/mantil/signup/backend/api/report"
)

func main() {
	var api = report.New()
	mantil.LambdaHandler(api)
}
