on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test workspace
      working-directory: ./domain
      run: go test -v ./...
    - name: Test controller
      working-directory: ./cli/controller
      run: go test -v ./...
    - name: Test all
      working-directory:
      run: go test ./...
