on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    # - name: Test domain
    #   working-directory: ./domain
    #   run: go test -v ./...
    # - name: Test controller
    #   working-directory: ./cli/controller
    #   run: go test -v ./...
    # - name: Test all
    #   working-directory:
    #   run: go test ./...
    - name: Configure AWS Credentials to mantil-io account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Build cli and deploy functions
      run: ./scripts/deploy_github_action.sh
    - name: Configure AWS Credentials to org5 account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::052548195718:role/OrganizationAccountAccessRole
        aws-region: eu-central-1
        role-skip-session-tagging: true
    - name: Integration Test
      run: go test -v
