on: [push, pull_request]
name: tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: mantil

    - name: Checkout infrastructure repo
      uses: actions/checkout@v2
      with:
        repository: mantil-io/infrastructure
        token: ${{ secrets.gh_pat_clone_infrastructure }} # `GH_PAT` is a secret that contains your PAT
        path: infrastructure

    - name: Configure AWS Credentials for mantil-io account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Build cli and deploy functions
      working-directory: mantil
      run: ./scripts/deploy_github_action.sh

    - name: Run unit tests
      working-directory: mantil
      run: go test -v ./aws/... ./cli/... ./domain/... ./kit/... ./node/...

    - name: Configure AWS Credentials for unit-test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::418101788216:role/OrganizationAccountAccessRole
        aws-region: eu-central-1
        role-skip-session-tagging: true
        role-duration-seconds: 3600      # 1h

    - name: Run end to end tests
      working-directory: mantil/test
      run: go test -v --timeout 1h
